name: OmniTiny
version: 1.0
main: me.user.omnitiny.OmniTiny
api-version: '1.21'
description: Плагин на уменьшение игрока и уютные взаимодействия.
author: user

commands:
  scale:
    description: Изменить свой размер (например, /scale 0.18)
    usage: /scale <число>
  v:
    description: Слезть с другого игрока или встать
    usage: /v
  crawl:
    description: Лечь на живот и ползать
    usage: /crawl
  sit:
    description: Присесть на землю
    usage: /sit
  lay:
    description: Лечь на землю отдохнуть
    usage: /lay
  hug:
    description: Обнять ближайшего игрока за ногу
    usage: /hug
