name: Build OmniTiny Mod
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Generate Wrapper
        run: gradle wrapper # ЭТА СТРОКА САМА СОЗДАСТ ГРАДЛ
      - name: Build Mod
        run: chmod +x gradlew && ./gradlew build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OmniTiny-Mod
          path: build/libs/*.jar
